<template><div><p>1、查询&quot;语文&quot;课程比&quot;数学&quot;课程成绩高的学生的性别及课程分数</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code>三表联查：
<span class="token keyword">select</span> s<span class="token punctuation">.</span><span class="token operator">*</span><span class="token punctuation">,</span> sc1<span class="token punctuation">.</span>s_score <span class="token string">'语文分数'</span><span class="token punctuation">,</span> sc2<span class="token punctuation">.</span>s_score <span class="token string">'数学分数'</span>
<span class="token keyword">from</span> score sc1
         <span class="token keyword">join</span> score sc2
         <span class="token keyword">join</span> student s <span class="token keyword">on</span> sc1<span class="token punctuation">.</span>s_id <span class="token operator">=</span> sc2<span class="token punctuation">.</span>s_id <span class="token operator">and</span> sc1<span class="token punctuation">.</span>s_id <span class="token operator">=</span> s<span class="token punctuation">.</span>s_id
<span class="token keyword">where</span> sc1<span class="token punctuation">.</span>c_id <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token keyword">select</span> c_id <span class="token keyword">from</span> course <span class="token keyword">where</span> c_name <span class="token operator">=</span> <span class="token string">'语文'</span><span class="token punctuation">)</span>
  <span class="token operator">and</span> sc2<span class="token punctuation">.</span>c_id <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token keyword">select</span> c_id <span class="token keyword">from</span> course <span class="token keyword">where</span> c_name <span class="token operator">=</span> <span class="token string">'数学'</span><span class="token punctuation">)</span>
  <span class="token operator">and</span> sc1<span class="token punctuation">.</span>s_score <span class="token operator">></span> sc2<span class="token punctuation">.</span>s_score
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>2、查询&quot;语文&quot;课程比&quot;数学&quot;课程成绩低的学生的性别及课程分数</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code><span class="token keyword">select</span> s<span class="token punctuation">.</span><span class="token operator">*</span><span class="token punctuation">,</span> sc1<span class="token punctuation">.</span>s_score <span class="token string">'语文分数'</span><span class="token punctuation">,</span> sc2<span class="token punctuation">.</span>s_score <span class="token string">'数学分数'</span>
<span class="token keyword">from</span> score sc1
         <span class="token keyword">join</span> score sc2
         <span class="token keyword">join</span> student s <span class="token keyword">on</span> sc1<span class="token punctuation">.</span>s_id <span class="token operator">=</span> sc2<span class="token punctuation">.</span>s_id <span class="token operator">and</span> sc1<span class="token punctuation">.</span>s_id <span class="token operator">=</span> s<span class="token punctuation">.</span>s_id
<span class="token keyword">where</span> sc1<span class="token punctuation">.</span>c_id <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token keyword">select</span> c_id <span class="token keyword">from</span> course <span class="token keyword">where</span> c_name <span class="token operator">=</span> <span class="token string">'语文'</span><span class="token punctuation">)</span>
  <span class="token operator">and</span> sc2<span class="token punctuation">.</span>c_id <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token keyword">select</span> c_id <span class="token keyword">from</span> course <span class="token keyword">where</span> c_name <span class="token operator">=</span> <span class="token string">'数学'</span><span class="token punctuation">)</span>
  <span class="token operator">and</span> sc1<span class="token punctuation">.</span>s_score <span class="token operator">&lt;</span> sc2<span class="token punctuation">.</span>s_score
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>3、查询平均成绩大于等于60分的同学的学生编号和学生姓名和平均成绩</p>
<p>4、查询平均成绩小于60分的同学的学生编号和学生姓名和平均成绩(包括有成绩的和无成绩的)</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code>求平均分不能使用avg，应该使用总分<span class="token operator">/</span>总课程数
<span class="token keyword">select</span> s<span class="token punctuation">.</span>s_id<span class="token punctuation">,</span> s_name<span class="token punctuation">,</span> ifnull<span class="token punctuation">(</span><span class="token function">sum</span><span class="token punctuation">(</span>s_score<span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span> <span class="token operator">/</span> <span class="token punctuation">(</span><span class="token keyword">select</span> <span class="token function">count</span><span class="token punctuation">(</span><span class="token operator">*</span><span class="token punctuation">)</span> <span class="token keyword">from</span> course<span class="token punctuation">)</span> av
<span class="token keyword">from</span> student s
         <span class="token keyword">left</span> <span class="token keyword">join</span> score sc <span class="token keyword">on</span> s<span class="token punctuation">.</span>s_id <span class="token operator">=</span> sc<span class="token punctuation">.</span>s_id
<span class="token keyword">group</span> <span class="token keyword">by</span> s<span class="token punctuation">.</span>s_id
<span class="token keyword">having</span> av <span class="token operator">&lt;</span> <span class="token number">60</span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>5、查询所有同学的学生编号、学生姓名、选课总数、所有课程的总成绩</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code><span class="token keyword">select</span> s<span class="token punctuation">.</span>s_id<span class="token punctuation">,</span> s_name<span class="token punctuation">,</span> <span class="token function">count</span><span class="token punctuation">(</span>c_id<span class="token punctuation">)</span> <span class="token string">'选课总数'</span><span class="token punctuation">,</span> <span class="token function">sum</span><span class="token punctuation">(</span>s_score<span class="token punctuation">)</span> <span class="token string">'总成绩'</span>
<span class="token keyword">from</span> student s
         <span class="token keyword">left</span> <span class="token keyword">join</span> score sc <span class="token keyword">on</span> s<span class="token punctuation">.</span>s_id <span class="token operator">=</span> sc<span class="token punctuation">.</span>s_id
<span class="token keyword">group</span> <span class="token keyword">by</span> s<span class="token punctuation">.</span>s_id
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>6、查询&quot;王&quot;姓老师的数量</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code><span class="token keyword">select</span> <span class="token function">count</span><span class="token punctuation">(</span><span class="token operator">*</span><span class="token punctuation">)</span> <span class="token keyword">from</span> teacher <span class="token keyword">where</span> t_name <span class="token operator">like</span> <span class="token string">'王%'</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>7、查询学过&quot;张三&quot;老师授课的同学的信息</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code><span class="token keyword">select</span> s<span class="token punctuation">.</span><span class="token operator">*</span>
<span class="token keyword">from</span> teacher t
         <span class="token keyword">join</span> course c
         <span class="token keyword">join</span> score sc
         <span class="token keyword">join</span> student s <span class="token keyword">on</span> t<span class="token punctuation">.</span>t_id <span class="token operator">=</span> c<span class="token punctuation">.</span>t_id <span class="token operator">and</span> c<span class="token punctuation">.</span>c_id <span class="token operator">=</span> sc<span class="token punctuation">.</span>c_id <span class="token operator">and</span> sc<span class="token punctuation">.</span>s_id <span class="token operator">=</span> s<span class="token punctuation">.</span>s_id
<span class="token keyword">where</span> t_name <span class="token operator">=</span> <span class="token string">'张三'</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>8、查询学过编号为&quot;01&quot;并且也学过编号为&quot;02&quot;的课程的同学的信息</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code><span class="token keyword">select</span> s<span class="token punctuation">.</span><span class="token operator">*</span><span class="token punctuation">,</span> sc1<span class="token punctuation">.</span>s_score <span class="token string">'01'</span><span class="token punctuation">,</span> sc2<span class="token punctuation">.</span>s_score <span class="token string">'02'</span>
<span class="token keyword">from</span> student s
         <span class="token keyword">join</span> score sc1
         <span class="token keyword">join</span> score sc2 <span class="token keyword">on</span> sc1<span class="token punctuation">.</span>s_id <span class="token operator">=</span> sc2<span class="token punctuation">.</span>s_id <span class="token operator">and</span> sc1<span class="token punctuation">.</span>s_id <span class="token operator">=</span> s<span class="token punctuation">.</span>s_id
<span class="token keyword">where</span> sc1<span class="token punctuation">.</span>c_id <span class="token operator">=</span> <span class="token string">'01'</span>
  <span class="token operator">and</span> sc2<span class="token punctuation">.</span>c_id <span class="token operator">=</span> <span class="token string">'02'</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>9、按平均成绩从高到低显示所有学生的所有课程的成绩以及平均成绩</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code>s_id<span class="token punctuation">,</span>  语文   数学    英语   平均成绩

<span class="token keyword">select</span> s<span class="token punctuation">.</span>s_id<span class="token punctuation">,</span>
       s_name<span class="token punctuation">,</span>
       <span class="token function">sum</span><span class="token punctuation">(</span>s_score<span class="token punctuation">)</span> <span class="token operator">/</span> <span class="token punctuation">(</span><span class="token keyword">select</span> <span class="token function">count</span><span class="token punctuation">(</span><span class="token operator">*</span><span class="token punctuation">)</span> <span class="token keyword">from</span> course<span class="token punctuation">)</span> av<span class="token punctuation">,</span>
       <span class="token function">max</span><span class="token punctuation">(</span><span class="token keyword">case</span> <span class="token keyword">when</span> c_id <span class="token operator">=</span> <span class="token string">'01'</span> <span class="token keyword">then</span> s_score <span class="token keyword">end</span><span class="token punctuation">)</span>  <span class="token string">'语文'</span><span class="token punctuation">,</span>
       <span class="token function">max</span><span class="token punctuation">(</span><span class="token keyword">case</span> <span class="token keyword">when</span> c_id <span class="token operator">=</span> <span class="token string">'02'</span> <span class="token keyword">then</span> s_score <span class="token keyword">end</span><span class="token punctuation">)</span>  <span class="token string">'数学'</span><span class="token punctuation">,</span>
       <span class="token function">max</span><span class="token punctuation">(</span><span class="token keyword">case</span> <span class="token keyword">when</span> c_id <span class="token operator">=</span> <span class="token string">'03'</span> <span class="token keyword">then</span> s_score <span class="token keyword">end</span><span class="token punctuation">)</span>  <span class="token string">'英语'</span>
<span class="token keyword">from</span> student s
         <span class="token keyword">left</span> <span class="token keyword">join</span> score sc <span class="token keyword">on</span> s<span class="token punctuation">.</span>s_id <span class="token operator">=</span> sc<span class="token punctuation">.</span>s_id
<span class="token keyword">group</span> <span class="token keyword">by</span> s<span class="token punctuation">.</span>s_id
<span class="token keyword">order</span> <span class="token keyword">by</span> av <span class="token keyword">desc</span>


分组过程中，对遍历到的每条数据，都会进行三次<span class="token keyword">case</span>  <span class="token keyword">when</span> 判断，则一个学生的三门成绩最终以三行存在，而各门课程的成绩应为三行中的最大值，所以应该使用max
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>10、查询各科成绩最高分、最低分和平均分：以如下形式显示：课程ID，课程name，最高分，最低分，平均分，及格率，中等率，优良率，优秀率 (及格为&gt;=60，中等为：70-80，优良为：80-90，优秀为：&gt;=90)</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code><span class="token keyword">select</span> c<span class="token punctuation">.</span>c_id<span class="token punctuation">,</span>
       c_name<span class="token punctuation">,</span>
       <span class="token function">max</span><span class="token punctuation">(</span>s_score<span class="token punctuation">)</span>                                                                                               <span class="token string">'最高分'</span><span class="token punctuation">,</span>
       <span class="token function">min</span><span class="token punctuation">(</span>s_score<span class="token punctuation">)</span>                                                                                               <span class="token string">'最低分'</span><span class="token punctuation">,</span>
       <span class="token function">avg</span><span class="token punctuation">(</span>s_score<span class="token punctuation">)</span><span class="token punctuation">,</span>
       concat<span class="token punctuation">(</span><span class="token function">round</span><span class="token punctuation">(</span><span class="token function">sum</span><span class="token punctuation">(</span><span class="token keyword">case</span> <span class="token keyword">when</span> s_score <span class="token operator">>=</span> <span class="token number">90</span> <span class="token keyword">then</span> <span class="token number">1</span> <span class="token keyword">else</span> <span class="token number">0</span> <span class="token keyword">end</span><span class="token punctuation">)</span> <span class="token operator">/</span> <span class="token function">count</span><span class="token punctuation">(</span>s_id<span class="token punctuation">)</span> <span class="token operator">*</span> <span class="token number">100</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'%'</span><span class="token punctuation">)</span>                  <span class="token string">'优秀率'</span><span class="token punctuation">,</span>
       concat<span class="token punctuation">(</span><span class="token function">round</span><span class="token punctuation">(</span><span class="token function">sum</span><span class="token punctuation">(</span><span class="token keyword">case</span> <span class="token keyword">when</span> s_score <span class="token operator">>=</span> <span class="token number">80</span> <span class="token operator">and</span> s_score <span class="token operator">&lt;</span> <span class="token number">90</span> <span class="token keyword">then</span> <span class="token number">1</span> <span class="token keyword">else</span> <span class="token number">0</span> <span class="token keyword">end</span><span class="token punctuation">)</span> <span class="token operator">/</span> <span class="token function">count</span><span class="token punctuation">(</span>s_id<span class="token punctuation">)</span> <span class="token operator">*</span> <span class="token number">100</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'%'</span><span class="token punctuation">)</span> <span class="token string">'优良率'</span><span class="token punctuation">,</span>
       concat<span class="token punctuation">(</span><span class="token function">round</span><span class="token punctuation">(</span><span class="token function">sum</span><span class="token punctuation">(</span><span class="token keyword">case</span> <span class="token keyword">when</span> s_score <span class="token operator">>=</span> <span class="token number">70</span> <span class="token operator">and</span> s_score <span class="token operator">&lt;</span> <span class="token number">80</span> <span class="token keyword">then</span> <span class="token number">1</span> <span class="token keyword">else</span> <span class="token number">0</span> <span class="token keyword">end</span><span class="token punctuation">)</span> <span class="token operator">/</span> <span class="token function">count</span><span class="token punctuation">(</span>s_id<span class="token punctuation">)</span> <span class="token operator">*</span> <span class="token number">100</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'%'</span><span class="token punctuation">)</span> <span class="token string">'中等率'</span><span class="token punctuation">,</span>
       concat<span class="token punctuation">(</span><span class="token function">round</span><span class="token punctuation">(</span><span class="token function">sum</span><span class="token punctuation">(</span><span class="token keyword">case</span> <span class="token keyword">when</span> s_score <span class="token operator">>=</span> <span class="token number">60</span> <span class="token keyword">then</span> <span class="token number">1</span> <span class="token keyword">else</span> <span class="token number">0</span> <span class="token keyword">end</span><span class="token punctuation">)</span> <span class="token operator">/</span> <span class="token function">count</span><span class="token punctuation">(</span>s_id<span class="token punctuation">)</span> <span class="token operator">*</span> <span class="token number">100</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'%'</span><span class="token punctuation">)</span>                  <span class="token string">'及格率'</span>
<span class="token keyword">from</span> course c
         <span class="token keyword">left</span> <span class="token keyword">join</span> score sc <span class="token keyword">on</span> c<span class="token punctuation">.</span>c_id <span class="token operator">=</span> sc<span class="token punctuation">.</span>c_id
<span class="token keyword">group</span> <span class="token keyword">by</span> c<span class="token punctuation">.</span>c_id

concat<span class="token punctuation">(</span><span class="token string">''</span><span class="token punctuation">,</span><span class="token string">'%'</span><span class="token punctuation">)</span>  <span class="token comment">-- 拼接</span>
保留小数函数：
	<span class="token function">round</span><span class="token punctuation">(</span>x<span class="token punctuation">,</span>d<span class="token punctuation">)</span>  <span class="token comment">-- 四舍五入，d表示保留几位   x表示小数</span>
	<span class="token keyword">truncate</span><span class="token punctuation">(</span>x<span class="token punctuation">,</span>d<span class="token punctuation">)</span> <span class="token comment">-- 截取几位小数  x：小数   d：截取几位小数	</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>11、查询每门科目成绩都在60分及以上的学生id，姓名，成绩</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code><span class="token number">1.</span> <span class="token function">max</span><span class="token punctuation">(</span><span class="token keyword">case</span> <span class="token keyword">when</span><span class="token punctuation">)</span>

<span class="token keyword">select</span> s<span class="token punctuation">.</span>s_id<span class="token punctuation">,</span>
       s_name<span class="token punctuation">,</span>
       <span class="token function">max</span><span class="token punctuation">(</span><span class="token keyword">case</span> <span class="token keyword">when</span> c_id <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token keyword">select</span> c_id <span class="token keyword">from</span> course <span class="token keyword">where</span> c_name <span class="token operator">=</span> <span class="token string">'语文'</span><span class="token punctuation">)</span> <span class="token keyword">then</span> s_score <span class="token keyword">end</span><span class="token punctuation">)</span> chinese<span class="token punctuation">,</span>
       <span class="token function">max</span><span class="token punctuation">(</span><span class="token keyword">case</span> <span class="token keyword">when</span> c_id <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token keyword">select</span> c_id <span class="token keyword">from</span> course <span class="token keyword">where</span> c_name <span class="token operator">=</span> <span class="token string">'数学'</span><span class="token punctuation">)</span> <span class="token keyword">then</span> s_score <span class="token keyword">end</span><span class="token punctuation">)</span> math<span class="token punctuation">,</span>
       <span class="token function">max</span><span class="token punctuation">(</span><span class="token keyword">case</span> <span class="token keyword">when</span> c_id <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token keyword">select</span> c_id <span class="token keyword">from</span> course <span class="token keyword">where</span> c_name <span class="token operator">=</span> <span class="token string">'英语'</span><span class="token punctuation">)</span> <span class="token keyword">then</span> s_score <span class="token keyword">end</span><span class="token punctuation">)</span> english
<span class="token keyword">from</span> student s
         <span class="token keyword">join</span> score sc <span class="token keyword">on</span> s<span class="token punctuation">.</span>s_id <span class="token operator">=</span> sc<span class="token punctuation">.</span>s_id
<span class="token keyword">group</span> <span class="token keyword">by</span> s<span class="token punctuation">.</span>s_id
<span class="token keyword">having</span> chinese <span class="token operator">>=</span> <span class="token number">60</span>
   <span class="token operator">and</span> math <span class="token operator">>=</span> <span class="token number">60</span>
   <span class="token operator">and</span> english <span class="token operator">>=</span> <span class="token number">60</span>

或：
将成绩表视为<span class="token number">3</span>份，分别作为语文成绩表，且分数<span class="token operator">>=</span><span class="token number">60</span>   数学成绩表，且分数<span class="token operator">>=</span><span class="token number">60</span>   英语成绩表  且分数<span class="token operator">>=</span><span class="token number">60</span>

三张成绩表自连接，最后和学生表连接

<span class="token keyword">select</span> s<span class="token punctuation">.</span>s_id<span class="token punctuation">,</span> s_name<span class="token punctuation">,</span> sc1<span class="token punctuation">.</span>s_score <span class="token string">'语文'</span><span class="token punctuation">,</span> sc2<span class="token punctuation">.</span>s_score <span class="token string">'数学'</span><span class="token punctuation">,</span> sc3<span class="token punctuation">.</span>s_score <span class="token string">'英语'</span>
<span class="token keyword">from</span> student s
         <span class="token keyword">join</span> score sc1
         <span class="token keyword">join</span> score sc2
         <span class="token keyword">join</span> score sc3
              <span class="token keyword">on</span> sc1<span class="token punctuation">.</span>s_id <span class="token operator">=</span> sc2<span class="token punctuation">.</span>s_id <span class="token operator">and</span> sc2<span class="token punctuation">.</span>s_id <span class="token operator">=</span> sc3<span class="token punctuation">.</span>s_id <span class="token operator">and</span> sc1<span class="token punctuation">.</span>s_id <span class="token operator">=</span> s<span class="token punctuation">.</span>s_id
<span class="token keyword">where</span> sc1<span class="token punctuation">.</span>c_id <span class="token operator">=</span> <span class="token string">'01'</span>
  <span class="token operator">and</span> sc1<span class="token punctuation">.</span>s_score <span class="token operator">>=</span> <span class="token number">60</span>
  <span class="token operator">and</span> sc2<span class="token punctuation">.</span>c_id <span class="token operator">=</span> <span class="token string">'02'</span>
  <span class="token operator">and</span> sc2<span class="token punctuation">.</span>s_score <span class="token operator">>=</span> <span class="token number">60</span>
  <span class="token operator">and</span> sc3<span class="token punctuation">.</span>c_id <span class="token operator">=</span> <span class="token string">'03'</span>
  <span class="token operator">and</span> sc3<span class="token punctuation">.</span>s_score <span class="token operator">>=</span> <span class="token number">60</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>12、查询至少有一门科目成绩在90分以上的学生id，姓名，成绩</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code><span class="token keyword">select</span> s<span class="token punctuation">.</span>s_id<span class="token punctuation">,</span>
       s_name<span class="token punctuation">,</span>
       <span class="token function">max</span><span class="token punctuation">(</span><span class="token keyword">case</span> <span class="token keyword">when</span> c_id <span class="token operator">=</span> <span class="token string">'01'</span> <span class="token keyword">then</span> s_score <span class="token keyword">end</span><span class="token punctuation">)</span> <span class="token string">'语文'</span><span class="token punctuation">,</span>
       <span class="token function">max</span><span class="token punctuation">(</span><span class="token keyword">case</span> <span class="token keyword">when</span> c_id <span class="token operator">=</span> <span class="token string">'02'</span> <span class="token keyword">then</span> s_score <span class="token keyword">end</span><span class="token punctuation">)</span> <span class="token string">'数学'</span><span class="token punctuation">,</span>
       <span class="token function">max</span><span class="token punctuation">(</span><span class="token keyword">case</span> <span class="token keyword">when</span> c_id <span class="token operator">=</span> <span class="token string">'03'</span> <span class="token keyword">then</span> s_score <span class="token keyword">end</span><span class="token punctuation">)</span> <span class="token string">'英语'</span>
<span class="token keyword">from</span> student s
         <span class="token keyword">join</span> score sc <span class="token keyword">on</span> s<span class="token punctuation">.</span>s_id <span class="token operator">=</span> sc<span class="token punctuation">.</span>s_id
<span class="token keyword">group</span> <span class="token keyword">by</span> sc<span class="token punctuation">.</span>s_id
<span class="token keyword">having</span> <span class="token function">max</span><span class="token punctuation">(</span>s_score<span class="token punctuation">)</span> <span class="token operator">></span> <span class="token number">90</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>13、查询所有科目成绩总和在240分及以上的学生id，姓名，和成绩总和，降序排列</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code><span class="token keyword">select</span> s<span class="token punctuation">.</span>s_id<span class="token punctuation">,</span> s_name<span class="token punctuation">,</span> <span class="token function">sum</span><span class="token punctuation">(</span>s_score<span class="token punctuation">)</span> sum
<span class="token keyword">from</span> student s
         <span class="token keyword">join</span> score sc <span class="token keyword">on</span> s<span class="token punctuation">.</span>s_id <span class="token operator">=</span> sc<span class="token punctuation">.</span>s_id
<span class="token keyword">group</span> <span class="token keyword">by</span> s<span class="token punctuation">.</span>s_id
<span class="token keyword">having</span> sum <span class="token operator">>=</span> <span class="token number">240</span>
<span class="token keyword">order</span> <span class="token keyword">by</span> sum <span class="token keyword">desc</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>14、查询每个科目成绩最高的学生的学生id，姓名，写在一个表里</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code><span class="token keyword">create</span> <span class="token keyword">table</span> tname <span class="token keyword">as</span> <span class="token keyword">select</span><span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span>

<span class="token number">1.</span> 查询每门科目的最高分
<span class="token number">2.</span> 根据科目id和对应的最高分到成绩表中查询对应的学生id
<span class="token number">3.</span> 根据学生id到学生表查询学生数据

<span class="token keyword">create</span> <span class="token keyword">table</span> new_table <span class="token keyword">as</span>
<span class="token keyword">select</span> s<span class="token punctuation">.</span>s_id<span class="token punctuation">,</span> s_name<span class="token punctuation">,</span> tmp<span class="token punctuation">.</span>c_id<span class="token punctuation">,</span> tmp<span class="token punctuation">.</span>max
<span class="token keyword">from</span> score sc
         <span class="token keyword">join</span> student s
         <span class="token keyword">join</span> <span class="token punctuation">(</span><span class="token keyword">select</span> c_id<span class="token punctuation">,</span> <span class="token function">max</span><span class="token punctuation">(</span>s_score<span class="token punctuation">)</span> max <span class="token keyword">from</span> score <span class="token keyword">group</span> <span class="token keyword">by</span> c_id<span class="token punctuation">)</span> tmp
              <span class="token keyword">on</span> sc<span class="token punctuation">.</span>c_id <span class="token operator">=</span> tmp<span class="token punctuation">.</span>c_id <span class="token operator">and</span> sc<span class="token punctuation">.</span>s_score <span class="token operator">=</span> tmp<span class="token punctuation">.</span>max <span class="token operator">and</span> sc<span class="token punctuation">.</span>s_id <span class="token operator">=</span> s<span class="token punctuation">.</span>s_id
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>15、查询每个科目成绩最低的学生的学生id，姓名</p>
<p>16、查询目前没有安排课程的老师姓名</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code>思路:查询老师教授的课程<span class="token punctuation">,</span>筛选课程id为<span class="token boolean">null</span>值的数据

<span class="token keyword">select</span> t_name <span class="token keyword">from</span> teacher t <span class="token keyword">left</span> <span class="token keyword">join</span> course c <span class="token keyword">on</span> t<span class="token punctuation">.</span>t_id<span class="token operator">=</span>c<span class="token punctuation">.</span>t_id <span class="token keyword">where</span> c_id <span class="token operator">is</span> <span class="token boolean">null</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>17、将之前老师表的英文名字转化为大写</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code>转换大小写函数:
	upper<span class="token punctuation">(</span>col<span class="token punctuation">)</span>    lower<span class="token punctuation">(</span>col<span class="token punctuation">)</span>
<span class="token keyword">update</span> teacher <span class="token keyword">set</span> t_name<span class="token operator">=</span>upper<span class="token punctuation">(</span>t_name<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>18、查询学生表中重复的姓名</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code>姓名重复的判断:判断姓名出现的次数<span class="token punctuation">,</span>若大于<span class="token number">1</span><span class="token punctuation">,</span>则重复
<span class="token keyword">select</span> s_name <span class="token keyword">from</span> student <span class="token keyword">group</span> <span class="token keyword">by</span> s_name <span class="token keyword">having</span> <span class="token function">count</span><span class="token punctuation">(</span>s_id<span class="token punctuation">)</span><span class="token operator">></span><span class="token number">1</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>19、统计各科成绩各分数段人数：课程编号,课程名称,[100-85],[85-70],[70-60],[0-60]及所占百分比</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code><span class="token keyword">select</span> c<span class="token punctuation">.</span>c_id<span class="token punctuation">,</span>
       c_name<span class="token punctuation">,</span>
       <span class="token function">count</span><span class="token punctuation">(</span>s_id<span class="token punctuation">)</span><span class="token punctuation">,</span>
       <span class="token function">sum</span><span class="token punctuation">(</span><span class="token keyword">case</span> <span class="token keyword">when</span> s_score <span class="token operator">>=</span> <span class="token number">85</span> <span class="token operator">and</span> s_score <span class="token operator">&lt;=</span> <span class="token number">100</span> <span class="token keyword">then</span> <span class="token number">1</span> <span class="token keyword">else</span> <span class="token number">0</span> <span class="token keyword">end</span><span class="token punctuation">)</span> <span class="token string">'[100-85]'</span><span class="token punctuation">,</span>
       <span class="token function">sum</span><span class="token punctuation">(</span><span class="token keyword">case</span> <span class="token keyword">when</span> s_score <span class="token operator">>=</span> <span class="token number">70</span> <span class="token operator">and</span> s_score <span class="token operator">&lt;</span> <span class="token number">85</span> <span class="token keyword">then</span> <span class="token number">1</span> <span class="token keyword">else</span> <span class="token number">0</span> <span class="token keyword">end</span><span class="token punctuation">)</span> <span class="token string">'[85-70]'</span><span class="token punctuation">,</span>
       <span class="token function">sum</span><span class="token punctuation">(</span><span class="token keyword">case</span> <span class="token keyword">when</span> s_score <span class="token operator">>=</span> <span class="token number">60</span> <span class="token operator">and</span> s_score <span class="token operator">&lt;</span> <span class="token number">70</span> <span class="token keyword">then</span> <span class="token number">1</span> <span class="token keyword">else</span> <span class="token number">0</span> <span class="token keyword">end</span><span class="token punctuation">)</span> <span class="token string">'[70-60]'</span><span class="token punctuation">,</span>
       <span class="token function">sum</span><span class="token punctuation">(</span><span class="token keyword">case</span> <span class="token keyword">when</span> s_score <span class="token operator">&lt;</span> <span class="token number">60</span> <span class="token keyword">then</span> <span class="token number">1</span> <span class="token keyword">else</span> <span class="token number">0</span> <span class="token keyword">end</span><span class="token punctuation">)</span> <span class="token string">'[0-60]'</span><span class="token punctuation">,</span>
       concat<span class="token punctuation">(</span><span class="token function">round</span><span class="token punctuation">(</span><span class="token function">sum</span><span class="token punctuation">(</span><span class="token keyword">case</span> <span class="token keyword">when</span> s_score <span class="token operator">>=</span> <span class="token number">85</span> <span class="token operator">and</span> s_score <span class="token operator">&lt;=</span> <span class="token number">100</span> <span class="token keyword">then</span> <span class="token number">1</span> <span class="token keyword">else</span> <span class="token number">0</span> <span class="token keyword">end</span><span class="token punctuation">)</span> <span class="token operator">/</span> <span class="token function">count</span><span class="token punctuation">(</span>s_id<span class="token punctuation">)</span> <span class="token operator">*</span> <span class="token number">100</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">,</span><span class="token string">'%'</span><span class="token punctuation">)</span> <span class="token string">'[100-85]百分比'</span><span class="token punctuation">,</span>
       concat<span class="token punctuation">(</span><span class="token function">round</span><span class="token punctuation">(</span><span class="token function">sum</span><span class="token punctuation">(</span><span class="token keyword">case</span> <span class="token keyword">when</span> s_score <span class="token operator">>=</span> <span class="token number">70</span> <span class="token operator">and</span> s_score <span class="token operator">&lt;</span> <span class="token number">85</span> <span class="token keyword">then</span> <span class="token number">1</span> <span class="token keyword">else</span> <span class="token number">0</span> <span class="token keyword">end</span><span class="token punctuation">)</span> <span class="token operator">/</span> <span class="token function">count</span><span class="token punctuation">(</span>s_id<span class="token punctuation">)</span> <span class="token operator">*</span> <span class="token number">100</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">,</span><span class="token string">'%'</span><span class="token punctuation">)</span>   <span class="token string">'[85-70]百分比'</span><span class="token punctuation">,</span>
       concat<span class="token punctuation">(</span><span class="token function">round</span><span class="token punctuation">(</span><span class="token function">sum</span><span class="token punctuation">(</span><span class="token keyword">case</span> <span class="token keyword">when</span> s_score <span class="token operator">>=</span> <span class="token number">60</span> <span class="token operator">and</span> s_score <span class="token operator">&lt;</span> <span class="token number">70</span> <span class="token keyword">then</span> <span class="token number">1</span> <span class="token keyword">else</span> <span class="token number">0</span> <span class="token keyword">end</span><span class="token punctuation">)</span> <span class="token operator">/</span> <span class="token function">count</span><span class="token punctuation">(</span>s_id<span class="token punctuation">)</span> <span class="token operator">*</span> <span class="token number">100</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">,</span><span class="token string">'%'</span><span class="token punctuation">)</span>   <span class="token string">'[70-60]百分比'</span><span class="token punctuation">,</span>
       concat<span class="token punctuation">(</span><span class="token function">round</span><span class="token punctuation">(</span><span class="token function">sum</span><span class="token punctuation">(</span><span class="token keyword">case</span> <span class="token keyword">when</span> s_score <span class="token operator">&lt;</span> <span class="token number">60</span> <span class="token keyword">then</span> <span class="token number">1</span> <span class="token keyword">else</span> <span class="token number">0</span> <span class="token keyword">end</span><span class="token punctuation">)</span> <span class="token operator">/</span> <span class="token function">count</span><span class="token punctuation">(</span>s_id<span class="token punctuation">)</span> <span class="token operator">*</span> <span class="token number">100</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'%'</span><span class="token punctuation">)</span> <span class="token string">'[0-60]百分比'</span>
<span class="token keyword">from</span> course c
         <span class="token keyword">left</span> <span class="token keyword">join</span> score sc <span class="token keyword">on</span> c<span class="token punctuation">.</span>c_id <span class="token operator">=</span> sc<span class="token punctuation">.</span>c_id
<span class="token keyword">group</span> <span class="token keyword">by</span> c<span class="token punctuation">.</span>c_id
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>
